### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by shouse** [GeraudBourdin/Ti.AndroidSvgView#1]
Could you provide more info on what this does?

**Comment by shouse** [comment]
I didn't notice your other repo.  Could still do a few screenshots if ya wanted to. :)

**Comment by GeraudBourdin** [comment]
hi ! I didn't realize that this module could be visited so quickly, that's why i didn't made the "how to" stuff. May be i should do it before trying to make the ios version. If you whant to you can make it and send a pull request. For now, i am trying to find a way to do the ios version of this module (i am just a beginner with ios, so it could take time :) ). Thanks for your interrest !
